package sist.com.vo;

public class AbandonedAnimalVO {

	
	
	
	
}
/*
  	"ABANIMALCODE" NUMBER(20,0) NOT NULL ENABLE, 
	"ABTHUMBPIC" "URITYPE" NOT NULL ENABLE, 
	"FINDDATE" DATE NOT NULL ENABLE, 
	"FINDLOC" NVARCHAR2(100) NOT NULL ENABLE, 
	"BREEDCODE" NUMBER(7,0) NOT NULL ENABLE, 
	"ANIMALTYPECODE" NUMBER(7,0) NOT NULL ENABLE, 
	"ABCOLOR" NVARCHAR2(10) NOT NULL ENABLE, 
	"ABAGE" NUMBER(7,2) NOT NULL ENABLE, 
	"ABWEIGHT" NUMBER(7,2) NOT NULL ENABLE, 
	"NOTICENUM" NVARCHAR2(30) NOT NULL ENABLE, 
	"NOTICESTARTDATE" DATE NOT NULL ENABLE, 
	"NOTICEENDDATE" DATE NOT NULL ENABLE, 
	"ABPIC" "URITYPE" NOT NULL ENABLE, 
	"ABSTATE" NVARCHAR2(7) NOT NULL ENABLE, 
	"ABFEAT" NVARCHAR2(100), 
	"ABCOMMENT" NVARCHAR2(100), 
	"ABATTENTION" NUMBER, 
	"SEXCODE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"SHELTERCODE" NUMBER(7,0) NOT NULL ENABLE, 
	"ADDRESSCODE" NUMBER(7,0) 
 * 
 */
