package sist.com.vo;

public class BreedVO {

}

/*
    CREATE TABLE "BREED"
  	"BREEDCODE" NUMBER(7,0) NOT NULL ENABLE, 
	"BREEDNAME" NVARCHAR2(20) NOT NULL ENABLE, 
	"ANIMALTYPECODE" NUMBER(7,0) NOT NULL ENABLE, 
 */

/*
    CREATE TABLE "ANIMALTYPE" 
   	"ANIMALTYPECODE" NUMBER(7,0) NOT NULL ENABLE, 
	"ANIMALTYPENAME" NVARCHAR2(20) NOT NULL ENABLE/
 */