package sist.com.vo;

public class ShelterVO {

}

/*
 	"SHELTERCODE" NUMBER(7,0) NOT NULL ENABLE, 
	"SHELTERNAME" NVARCHAR2(50) NOT NULL ENABLE, 
	"MGMTAGENCYNAME" NVARCHAR2(20) NOT NULL ENABLE, 
	"SHELTERTYPE" NVARCHAR2(10) NOT NULL ENABLE, 
	"SHELTERDESIGDATE" DATE NOT NULL ENABLE, 
	"WEEKDAYSTARTTIME" TIMESTAMP (6) NOT NULL ENABLE, 
	"WEEKDAYENDTIME" TIMESTAMP (6) NOT NULL ENABLE, 
	"WEEKDAYADOPTSTARTTIME" TIMESTAMP (6), 
	"WEEKDAYADOPTENDTIME" TIMESTAMP (6), 
	"WEEKENDSTARTTIME" TIMESTAMP (6), 
	"WEEKENDENDTIME" TIMESTAMP (6), 
	"WEEKENDADOPTSTARTTIME" TIMESTAMP (6), 
	"WEEKENDADOPTENDTIME" TIMESTAMP (6), 
	"HOLIDAY" NVARCHAR2(20) NOT NULL ENABLE, 
	"VETCNT" NUMBER(5,0) NOT NULL ENABLE, 
	"SPECMGRCNT" NUMBER(5,0) NOT NULL ENABLE, 
	"DROFFICECNT" NUMBER(5,0), 
	"CARERMCNT" NUMBER(5,0), 
	"QUARANTINERMCNT" NUMBER(5,0), 
	"FOODSTRGRMCNT" NUMBER(5,0), 
	"VEHICLECNT" NUMBER(5,0), 
	"TEL" NUMBER(15,0) NOT NULL ENABLE, 
	"DATADATE" DATE NOT NULL ENABLE, 
	"ADDRESSCODE" NUMBER(7,0),  
 */
